# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "nct6775" "uinput" "uhid" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "amdgpu.runpm=0"       # Disable BACO runtime PM (your root cause)
    "amdgpu.cwsr_enable=0" # Disable compute queue switching (prevents eviction cascades)\
  ];

  networking = {
    useDHCP = lib.mkDefault true;
    # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;
    interfaces.enp37s0 = {
      wakeOnLan.enable = true;
    };
    firewall.allowedUDPPorts = [ 9 ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
